# Generated by Django 4.2.6 on 2023-11-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Artist's name")),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="User's name")),
            ],
        ),
        migrations.CreateModel(
            name="UserArtistPlays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plays",
                    models.IntegerField(
                        verbose_name="Number of times this user has played this artist"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.artists"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.users"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "artist"], name="user_artist_key")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userartistplays",
            constraint=models.UniqueConstraint(
                fields=("user", "artist"), name="user_artist_key"
            ),
        ),
    ]
